server:
  port: 8888
spring:
  application:
    name: config-server


# http 请求地址 与资源文件的映射关系  http://localhost:8888/foo/dev
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties
  # 读取git仓库上的文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo  # git仓库地址下的相对地址 多个用逗号","分割。
          username:
          password:
      label: master



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#  # 如果使用读取本地文件
#  profiles:
#    active: local