
server:
  port: 8081

spring:
  application:
    name: sc-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能
          # 并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，
          #   这个router将以服务名开头的请求路径转发到对应的服务
#          enabled: true
          # 将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了）
          lowerCaseServiceId: true

          enabled: false
      # 或者手动配置  , 而且必须将前面的 enabled： true 改为false 。这样就只有一个routesId ，才进入
      routes:
        - id: clinet
          # lb://CLIENT即client服务的负载均衡地址
          uri: lb://CLIENT
          predicates:
            - Path=/demo/**
          filters:
            # 真正进入路由的会去掉 /demo的这个前缀
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/