server:
  port: 8989
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    # 注意命名不能下划线
    name: server-two

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
