
server:
  port: 8762

spring:
  application:
    name: client

eureka:
  client:
    # 表示将自己注册进Eureka Server默认为true
    register-with-eureka: true
    # 是否从Eureka Server抓去已有的注册信息，默认是true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/